name: Theme Request
description: Submit a theme request
labels: ["available", "theme"]

body:
  - type: input
    id: discord
    attributes:
      label: Discord username
      description: What's your Discord @username? (optional)
      placeholder: Foobar#1234 or @foobar
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Theme description
      description: A short and simple description of your theme request
      placeholder: This theme should look like ...
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Elaborate
      description: Include some more details about your theme request (optional)
      placeholder: This theme should use the font ...
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: Some additional references for your theme request (optional)
      placeholder: |
        https://betterdiscord.app/theme/Frosted%20Glass
        https://i.imgur.com/kYW2H5C.jpg

  - type: checkboxes
    id: rules
    attributes:
      label: Rules
      description: Before submitting make sure to read the [README](https://github.com/Revenge-mod/addon-requests#readme)
      options:
        - label: I have read the README and checked this wasn't already suggested
          required: true
